package io.github.aandreakis.dblog.state.jdbc;

import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Locale;

public final class JdbcStateStoreSchemaBootstrap {
  private JdbcStateStoreSchemaBootstrap() {}

  public static void initialize(Connection connection) throws SQLException {
    // This implementation does not version its state-store schema or provide automatic
    // migration. Operators upgrading the DBLog binary across schema-shape changes should reset
    // the local state files before starting the new binary (see docs/OPERATION.md §9.1.1).
    // STATE_STORE_META is a generic META_KEY/META_VALUE table used by other repositories (e.g.
    // stream bootstrap position) — it is not a schema-version marker despite its name.
    createTableIfMissing(
        connection,
        "STATE_STORE_META",
        "CREATE TABLE STATE_STORE_META (META_KEY VARCHAR(128) PRIMARY KEY, META_VALUE VARCHAR(2048) NOT NULL)");
    createTableIfMissing(
        connection,
        "STREAM_CHECKPOINT",
        "CREATE TABLE STREAM_CHECKPOINT (SOURCE_ID VARCHAR(255) PRIMARY KEY, POSITION_VALUE VARCHAR(8192) NOT NULL)");
    createTableIfMissing(
        connection,
        "DUMP_REQUEST",
        "CREATE TABLE DUMP_REQUEST (REQUEST_SEQUENCE BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, REQUEST_ID VARCHAR(255), SCOPE_VALUE VARCHAR(64) NOT NULL, DATABASE_NAME VARCHAR(255), SCHEMA_NAME_VALUE VARCHAR(255), TABLE_NAME_VALUE VARCHAR(255), CREATED_AT VARCHAR(128), UPDATED_AT VARCHAR(128))");
    createUniqueIndexIfMissing(
        connection,
        "DUMP_REQUEST",
        "DUMP_REQUEST_REQUEST_ID_UQ",
        "CREATE UNIQUE INDEX DUMP_REQUEST_REQUEST_ID_UQ ON DUMP_REQUEST (REQUEST_ID)");
    createTableIfMissing(
        connection,
        "DUMP_REQUEST_KEY",
        "CREATE TABLE DUMP_REQUEST_KEY (REQUEST_ID VARCHAR(255) NOT NULL, ORDINAL_POSITION INT NOT NULL, PRIMARY_KEY_LITERAL VARCHAR(8192) NOT NULL, PRIMARY KEY (REQUEST_ID, ORDINAL_POSITION))");
    createTableIfMissing(
        connection,
        "DUMP_REQUEST_STATUS",
        "CREATE TABLE DUMP_REQUEST_STATUS (REQUEST_ID VARCHAR(255) PRIMARY KEY, SCOPE_VALUE VARCHAR(64) NOT NULL, DATABASE_NAME VARCHAR(255), SCHEMA_NAME_VALUE VARCHAR(255), TABLE_NAME_VALUE VARCHAR(255), STATE_VALUE VARCHAR(64) NOT NULL, ACTIVE_LOW_WATERMARK VARCHAR(255), ACTIVE_HIGH_WATERMARK VARCHAR(255), FAILURE_REASON VARCHAR(8192), UPDATED_AT VARCHAR(128))");
    createTableIfMissing(
        connection,
        "DUMP_REQUEST_MISSING_KEY",
        "CREATE TABLE DUMP_REQUEST_MISSING_KEY (REQUEST_ID VARCHAR(255) NOT NULL, ORDINAL_POSITION INT NOT NULL, PRIMARY_KEY_LITERAL VARCHAR(8192) NOT NULL, PRIMARY KEY (REQUEST_ID, ORDINAL_POSITION))");
    createTableIfMissing(
        connection,
        "DUMP_TABLE_PROGRESS",
        "CREATE TABLE DUMP_TABLE_PROGRESS (JOB_ID VARCHAR(255) NOT NULL, TABLE_NAME_VALUE VARCHAR(1024) NOT NULL, SCHEMA_FINGERPRINT VARCHAR(255) NOT NULL, REQUEST_UPPER_BOUND_PRIMARY_KEY VARCHAR(8192), LAST_COMPLETED_PRIMARY_KEY VARCHAR(8192), ACTIVE_CHUNK_START_AFTER VARCHAR(8192), ACTIVE_LOW_WATERMARK VARCHAR(255), ACTIVE_HIGH_WATERMARK VARCHAR(255), CHUNK_COMPLETED INT NOT NULL, FAILURE_REASON VARCHAR(8192), PRIMARY KEY (JOB_ID, TABLE_NAME_VALUE))");
    createTableIfMissing(
        connection,
        "TABLE_SCHEMA_CURRENT",
        "CREATE TABLE TABLE_SCHEMA_CURRENT (TABLE_DISPLAY_NAME VARCHAR(1024) PRIMARY KEY, DATABASE_NAME VARCHAR(255) NOT NULL, SCHEMA_NAME_VALUE VARCHAR(255) NOT NULL, TABLE_NAME_VALUE VARCHAR(255) NOT NULL, PRIMARY_KEY_COLUMN VARCHAR(255) NOT NULL, FINGERPRINT VARCHAR(255) NOT NULL, REFRESHED_AT VARCHAR(128) NOT NULL)");
    createTableIfMissing(
        connection,
        "TABLE_SCHEMA_COLUMN",
        "CREATE TABLE TABLE_SCHEMA_COLUMN (TABLE_DISPLAY_NAME VARCHAR(1024) NOT NULL, ORDINAL_POSITION INT NOT NULL, COLUMN_NAME VARCHAR(255) NOT NULL, SOURCE_TYPE VARCHAR(255) NOT NULL, NEUTRAL_TYPE VARCHAR(64) NOT NULL, PRIMARY_KEY_FLAG INT NOT NULL, PRIMARY_KEY_ORDINAL INT NOT NULL DEFAULT 0, IGNORED_FLAG INT NOT NULL DEFAULT 0, NULLABLE_FLAG INT NOT NULL, PRIMARY KEY (TABLE_DISPLAY_NAME, ORDINAL_POSITION))");
    createTableIfMissing(
        connection,
        "TABLE_SCHEMA_OBSERVED",
        "CREATE TABLE TABLE_SCHEMA_OBSERVED (TABLE_DISPLAY_NAME VARCHAR(1024) PRIMARY KEY, DATABASE_NAME VARCHAR(255) NOT NULL, SCHEMA_NAME_VALUE VARCHAR(255) NOT NULL, TABLE_NAME_VALUE VARCHAR(255) NOT NULL, PRIMARY_KEY_COLUMN VARCHAR(255) NOT NULL, FINGERPRINT VARCHAR(255) NOT NULL, REFRESHED_AT VARCHAR(128) NOT NULL)");
    createTableIfMissing(
        connection,
        "TABLE_SCHEMA_OBSERVED_COLUMN",
        "CREATE TABLE TABLE_SCHEMA_OBSERVED_COLUMN (TABLE_DISPLAY_NAME VARCHAR(1024) NOT NULL, ORDINAL_POSITION INT NOT NULL, COLUMN_NAME VARCHAR(255) NOT NULL, SOURCE_TYPE VARCHAR(255) NOT NULL, NEUTRAL_TYPE VARCHAR(64) NOT NULL, PRIMARY_KEY_FLAG INT NOT NULL, PRIMARY_KEY_ORDINAL INT NOT NULL DEFAULT 0, IGNORED_FLAG INT NOT NULL DEFAULT 0, NULLABLE_FLAG INT NOT NULL, PRIMARY KEY (TABLE_DISPLAY_NAME, ORDINAL_POSITION))");
    createTableIfMissing(
        connection,
        "FULL_DUMP_REQUIRED_SIGNAL",
        "CREATE TABLE FULL_DUMP_REQUIRED_SIGNAL (SOURCE_ID VARCHAR(255) NOT NULL, TABLE_DISPLAY_NAME VARCHAR(1024) NOT NULL, DATABASE_NAME VARCHAR(255), SCHEMA_NAME_VALUE VARCHAR(255), TABLE_NAME_VALUE VARCHAR(255), REASON VARCHAR(8192) NOT NULL, DETECTED_AT VARCHAR(128) NOT NULL, PRIMARY KEY (SOURCE_ID, TABLE_DISPLAY_NAME))");
    createTableIfMissing(
        connection,
        "SCHEMA_UNCERTAINTY_SIGNAL",
        "CREATE TABLE SCHEMA_UNCERTAINTY_SIGNAL (SOURCE_ID VARCHAR(255) NOT NULL, TABLE_DISPLAY_NAME VARCHAR(1024) NOT NULL, DATABASE_NAME VARCHAR(255), SCHEMA_NAME_VALUE VARCHAR(255), TABLE_NAME_VALUE VARCHAR(255), REASON VARCHAR(8192) NOT NULL, FIRST_DETECTED_AT VARCHAR(128) NOT NULL, LAST_DETECTED_AT VARCHAR(128) NOT NULL, OCCURRENCE_COUNT INT NOT NULL, PRIMARY KEY (SOURCE_ID, TABLE_DISPLAY_NAME))");
  }

  private static void createTableIfMissing(Connection connection, String tableName, String ddl)
      throws SQLException {
    if (tableExists(connection, tableName)) {
      return;
    }
    try (Statement statement = connection.createStatement()) {
      statement.executeUpdate(ddl);
    } catch (SQLException e) {
      if (tableExists(connection, tableName)) {
        return;
      }
      throw e;
    }
  }

  private static boolean tableExists(Connection connection, String tableName) throws SQLException {
    DatabaseMetaData metadata = connection.getMetaData();
    try (ResultSet tables =
        metadata.getTables(null, null, tableName.toUpperCase(Locale.ROOT), new String[] {"TABLE"})) {
      return tables.next();
    }
  }

  private static void createUniqueIndexIfMissing(
      Connection connection, String tableName, String indexName, String ddl) throws SQLException {
    if (indexExists(connection, tableName, indexName)) {
      return;
    }
    try (Statement statement = connection.createStatement()) {
      statement.executeUpdate(ddl);
    } catch (SQLException e) {
      if (indexExists(connection, tableName, indexName)) {
        return;
      }
      throw new SQLException(
          "Failed to create unique index "
              + indexName
              + " for "
              + tableName
              + "; the state store may already contain duplicate logical request ids",
          e);
    }
  }

  private static boolean indexExists(Connection connection, String tableName, String indexName)
      throws SQLException {
    DatabaseMetaData metadata = connection.getMetaData();
    try (ResultSet indexes =
        metadata.getIndexInfo(null, null, tableName.toUpperCase(Locale.ROOT), true, false)) {
      while (indexes.next()) {
        String existingIndexName = indexes.getString("INDEX_NAME");
        if (existingIndexName != null && existingIndexName.equalsIgnoreCase(indexName)) {
          return true;
        }
      }
      return false;
    }
  }
}
