package io.github.aandreakis.dblog.state.h2;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

import io.github.aandreakis.dblog.core.model.OpaqueSourcePosition;
import io.github.aandreakis.dblog.core.model.TableId;
import io.github.aandreakis.dblog.core.request.DumpRequest;
import io.github.aandreakis.dblog.core.request.DumpRequestState;
import io.github.aandreakis.dblog.core.request.DumpRequestStatus;
import io.github.aandreakis.dblog.core.request.DumpScope;
import io.github.aandreakis.dblog.core.request.DumpTableProgress;
import io.github.aandreakis.dblog.core.schema.ColumnDefinition;
import io.github.aandreakis.dblog.core.schema.FullDumpRequiredSignal;
import io.github.aandreakis.dblog.core.schema.NeutralColumnType;
import io.github.aandreakis.dblog.core.schema.SchemaUncertaintySignal;
import io.github.aandreakis.dblog.core.schema.TableSchema;
import io.github.aandreakis.dblog.state.api.StoredDumpRequestDetail;
import java.nio.file.Path;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import java.time.Instant;
import java.util.List;
import java.util.concurrent.ConcurrentLinkedQueue;
import java.util.concurrent.CountDownLatch;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.TimeUnit;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

class H2RuntimeStateStoreTests {
  @TempDir Path tempDir;

  /**
   * Pins that a failure in the schema-bootstrap step of the {@link H2RuntimeStateStore}
   * constructor releases the Hikari connection pool lease before the exception propagates. The
   * constructor acquires the lease eagerly, then runs {@code
   * JdbcStateStoreSchemaBootstrap.initialize(connection)}. If that throws, the caller never
   * receives an instance and will never call {@link H2RuntimeStateStore#close()} — the lease
   * would otherwise stay in the registry until JVM exit.
   *
   * <p>Trigger: pre-populate the H2 file with a {@code DUMP_REQUEST} table missing the
   * {@code REQUEST_ID} column. {@code createTableIfMissing} skips it (table exists), then
   * {@code createUniqueIndexIfMissing} tries to create
   * {@code DUMP_REQUEST_REQUEST_ID_UQ ON DUMP_REQUEST (REQUEST_ID)}; H2 rejects the DDL because
   * the column does not exist.
   */
  @Test
  void releasesHikariLeaseWhenSchemaBootstrapFails() throws Exception {
    HikariLeaseRegistry.resetForTests();
    assertThat(HikariLeaseRegistry.activePoolCountForTests()).isEqualTo(0);

    Path databasePath = tempDir.resolve("next-bootstrap-fail-store");
    String jdbcUrl = H2RuntimeStateStore.h2JdbcUrl(databasePath);

    // Pre-populate the H2 file with a DUMP_REQUEST that has no REQUEST_ID column. The bootstrap
    // createTableIfMissing skips an existing table, then the unique-index creation fails because
    // REQUEST_ID doesn't exist.
    try (Connection setup = DriverManager.getConnection(jdbcUrl);
        Statement statement = setup.createStatement()) {
      statement.executeUpdate(
          "CREATE TABLE DUMP_REQUEST ("
              + "REQUEST_SEQUENCE BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
              + "SCOPE_VALUE VARCHAR(64) NOT NULL)");
    }

    assertThatThrownBy(() -> new H2RuntimeStateStore(databasePath))
        .isInstanceOf(RuntimeException.class);

    // The fix: despite the thrown constructor, the Hikari lease must be released.
    assertThat(HikariLeaseRegistry.activePoolCountForTests()).isEqualTo(0);
  }

  @Test
  void persistsCheckpointsAcrossReopenAndEnforcesSingleSourceOwnership() {
    Path databasePath = tempDir.resolve("next-state-store");

    try (H2RuntimeStateStore store = new H2RuntimeStateStore(databasePath)) {
      store.ownership().claimSourceOwnership("source-a");
      store.streamPositions().saveCheckpoint("source-a", new OpaqueSourcePosition("checkpoint-1"));
      store.streamPositions()
          .saveBootstrapPosition("source-a", new OpaqueSourcePosition("bootstrap-1"));
    }

    try (H2RuntimeStateStore reopened = new H2RuntimeStateStore(databasePath)) {
      reopened.ownership().claimSourceOwnership("source-a");
      assertThat(reopened.streamPositions().loadCheckpoint("source-a"))
          .contains(new OpaqueSourcePosition("checkpoint-1"));
      assertThat(reopened.streamPositions().loadBootstrapPosition("source-a")).isEmpty();
      assertThatThrownBy(() -> reopened.ownership().claimSourceOwnership("source-b"))
          .isInstanceOf(IllegalStateException.class)
          .hasMessageContaining("already owned by sourceId source-a");
    }
  }

  @Test
  void preservesPendingRequestOrderAndRetiresTerminalRequestsFromPendingCount() {
    Path databasePath = tempDir.resolve("next-request-store");
    TableId tableId = new TableId("source", "appdb", "widgets");
    TableSchema schema = contractSchema();
    DumpRequest queued = new DumpRequest("201", DumpScope.TABLE, tableId, List.of());
    DumpRequest active = new DumpRequest("202", DumpScope.TABLE, tableId, List.of());
    DumpRequest completed =
        DumpRequest.fromPrimaryKeyLiterals(
            "203", DumpScope.PRIMARY_KEYS, tableId, schema, List.of("1"));

    try (H2RuntimeStateStore store = new H2RuntimeStateStore(databasePath)) {
      store.dumpRequests().upsert(queued);
      store.dumpRequests().upsert(active);
      store.dumpRequests().upsert(completed);
      store.dumpRequests().saveStatus(DumpRequestStatus.active(active));

      assertThat(store.dumpRequests().countPending()).isEqualTo(3);
      assertThat(store.dumpRequests().loadPending())
          .extracting(DumpRequest::requestId)
          .containsExactly("201", "202", "203");

      store.dumpRequests()
          .saveStatus(DumpRequestStatus.completed(active, List.of()));
      store.dumpRequests()
          .saveStatus(DumpRequestStatus.completed(completed, List.of()));

      assertThat(store.dumpRequests().countPending()).isEqualTo(1);
      assertThat(store.dumpRequests().loadPending())
          .extracting(DumpRequest::requestId)
          .containsExactly("201");
    }
  }

  @Test
  void loadsDetailedRequestsWithStatusAndPrimaryKeyCollectionsInOneShape() {
    Path databasePath = tempDir.resolve("next-detailed-request-store");
    TableId tableId = new TableId("source", "appdb", "widgets");
    TableSchema schema = contractSchema();
    DumpRequest queued = new DumpRequest("301", DumpScope.TABLE, tableId, List.of());
    DumpRequest active =
        DumpRequest.fromPrimaryKeyLiterals(
            "302", DumpScope.PRIMARY_KEYS, tableId, schema, List.of("1", "2"));

    try (H2RuntimeStateStore store = new H2RuntimeStateStore(databasePath)) {
      store.dumpRequests().upsert(queued);
      store.dumpRequests().upsert(active);
      store.dumpRequests()
          .saveStatus(
              DumpRequestStatus.completed(
                  active,
                  schema.primaryKeyTuplesFromLiterals(List.of("2"))));

      List<StoredDumpRequestDetail> details = store.dumpRequests().loadAllDetailedWithStatus();
      assertThat(details).hasSize(2);
      assertThat(details)
          .extracting(detail -> detail.storedRequest().request().requestId())
          .containsExactly("301", "302");

      StoredDumpRequestDetail queuedDetail = details.get(0);
      assertThat(queuedDetail.status()).isNull();
      assertThat(queuedDetail.storedRequest().request().primaryKeyLiterals()).isEmpty();

      StoredDumpRequestDetail activeDetail =
          store.dumpRequests().loadRequestDetailedWithStatus("302").orElseThrow();
      assertThat(activeDetail.storedRequest().request().primaryKeyLiterals())
          .containsExactly("1", "2");
      assertThat(activeDetail.status()).isNotNull();
      assertThat(activeDetail.status().state()).isEqualTo(DumpRequestState.COMPLETED);
      assertThat(activeDetail.status().missingPrimaryKeyLiterals()).containsExactly("2");
    }
  }

  @Test
  void persistsContractObservedAndSignalStateIndependentlyAcrossReopen() {
    Path databasePath = tempDir.resolve("next-schema-store");
    TableSchema contractSchema = contractSchema();
    TableSchema observedSchema = observedSchema();

    try (H2RuntimeStateStore store = new H2RuntimeStateStore(databasePath)) {
      store.schemas().saveContractSchema(contractSchema);
      store.schemas().saveObservedSchema(observedSchema);
      store.schemas()
          .saveFullDumpRequiredSignal(
              new FullDumpRequiredSignal(
                  "source",
                  contractSchema.tableId(),
                  "full dump required because data loss was detected",
                  Instant.parse("2026-03-29T00:06:00Z")));
      store.schemas()
          .saveSchemaUncertaintySignal(
              new SchemaUncertaintySignal(
                  "source",
                  contractSchema.tableId(),
                  "schema continuity uncertain",
                  Instant.parse("2026-03-29T00:00:00Z"),
                  Instant.parse("2026-03-29T00:05:00Z"),
                  2));
    }

    try (H2RuntimeStateStore reopened = new H2RuntimeStateStore(databasePath)) {
      assertThat(reopened.schemas().loadContractSchema(contractSchema.tableId().displayName()))
          .contains(contractSchema);
      assertThat(reopened.schemas().loadObservedSchema(contractSchema.tableId().displayName()))
          .contains(observedSchema);
      assertThat(reopened.schemas().loadFullDumpRequiredSignals())
          .extracting(FullDumpRequiredSignal::reason)
          .contains("full dump required because data loss was detected");
      assertThat(reopened.schemas().loadSchemaUncertaintySignals()).hasSize(1);
      assertThat(reopened.schemas().loadSchemaUncertaintySignals().get(0).occurrenceCount())
          .isEqualTo(2);
    }
  }

  @Test
  void invalidatesDumpProgressAndRetiresNonTerminalRequestsForPkChange() {
    Path databasePath = tempDir.resolve("next-pk-invalidation-store");
    TableSchema schema = contractSchema();
    TableId tableId = schema.tableId();
    DumpRequest tableRequest = new DumpRequest("101", DumpScope.TABLE, tableId, List.of());
    DumpRequest allTablesRequest = new DumpRequest("102", DumpScope.ALL_TABLES, null, List.of());
    DumpRequest primaryKeysRequest =
        DumpRequest.fromPrimaryKeyLiterals(
            "103", DumpScope.PRIMARY_KEYS, tableId, schema, List.of("1"));
    DumpRequest completedRequest = new DumpRequest("104", DumpScope.TABLE, tableId, List.of());

    try (H2RuntimeStateStore store = new H2RuntimeStateStore(databasePath)) {
      store.streamPositions().saveCheckpoint("source", new OpaqueSourcePosition("checkpoint-1"));
      store.dumpRequests().upsert(tableRequest);
      store.dumpRequests().upsert(allTablesRequest);
      store.dumpRequests().upsert(primaryKeysRequest);
      store.dumpRequests().upsert(completedRequest);
      store.dumpRequests().saveStatus(DumpRequestStatus.active(tableRequest));
      store.dumpRequests().saveStatus(DumpRequestStatus.active(primaryKeysRequest));
      store.dumpRequests().saveStatus(DumpRequestStatus.completed(completedRequest, List.of()));
      store.dumpProgress()
          .save(
              DumpTableProgress.initial(
                      tableRequest.requestId(), tableId.displayName(), schema.fingerprint())
                  .captureRequestUpperBound(schema, "10"));
      store.schemas()
          .saveSchemaUncertaintySignal(
              new SchemaUncertaintySignal(
                  "source",
                  tableId,
                  "uncertain before invalidation",
                  Instant.parse("2026-03-29T00:00:00Z"),
                  Instant.parse("2026-03-29T00:00:00Z"),
                  1));

      store.invalidateRuntimeStateForPkChange(
          "source", "primary key changed and dump progress was invalidated");
    }

    try (H2RuntimeStateStore reopened = new H2RuntimeStateStore(databasePath)) {
      assertThat(reopened.streamPositions().loadCheckpoint("source"))
          .contains(new OpaqueSourcePosition("checkpoint-1"));
      assertThat(reopened.dumpProgress().load(tableRequest.requestId(), tableId.displayName()))
          .isEmpty();
      assertThat(reopened.dumpRequests().loadStatus(tableRequest.requestId()).orElseThrow().state())
          .isEqualTo(DumpRequestState.FAILED);
      assertThat(
              reopened.dumpRequests().loadStatus(allTablesRequest.requestId()).orElseThrow().state())
          .isEqualTo(DumpRequestState.FAILED);
      assertThat(
              reopened.dumpRequests()
                  .loadStatus(primaryKeysRequest.requestId())
                  .orElseThrow()
                  .state())
          .isEqualTo(DumpRequestState.FAILED);
      assertThat(reopened.dumpRequests().loadStatus(completedRequest.requestId()))
          .contains(DumpRequestStatus.completed(completedRequest, List.of()));
      assertThat(reopened.dumpRequests().loadPending()).isEmpty();
      assertThat(reopened.schemas().loadSchemaUncertaintySignals()).isEmpty();
    }
  }

  @Test
  void assignsUniqueGeneratedRequestIdsUnderConcurrentCreateLoad() throws Exception {
    Path databasePath = tempDir.resolve("next-concurrent-request-ids");
    TableId tableId = new TableId("source", "appdb", "widgets");
    int threadCount = 16;
    int requestsPerThread = 20;
    ExecutorService executor = Executors.newFixedThreadPool(threadCount);
    ConcurrentLinkedQueue<Throwable> failures = new ConcurrentLinkedQueue<>();
    ConcurrentLinkedQueue<String> requestIds = new ConcurrentLinkedQueue<>();
    CountDownLatch ready = new CountDownLatch(threadCount);
    CountDownLatch start = new CountDownLatch(1);
    CountDownLatch done = new CountDownLatch(threadCount);

    for (int worker = 0; worker < threadCount; worker++) {
      executor.submit(
          () -> {
            ready.countDown();
            try {
              start.await();
              for (int requestIndex = 0; requestIndex < requestsPerThread; requestIndex++) {
                try (H2RuntimeStateStore store = new H2RuntimeStateStore(databasePath)) {
                  requestIds.add(
                      store.dumpRequests()
                          .createGenerated(DumpScope.TABLE, tableId, List.of())
                          .requestId());
                }
              }
            } catch (Throwable failure) {
              failures.add(failure);
            } finally {
              done.countDown();
            }
          });
    }

    assertThat(ready.await(5, TimeUnit.SECONDS)).isTrue();
    start.countDown();
    assertThat(done.await(30, TimeUnit.SECONDS)).isTrue();
    executor.shutdownNow();

    assertThat(failures).isEmpty();
    assertThat(requestIds).hasSize(threadCount * requestsPerThread);
    assertThat(new java.util.LinkedHashSet<>(requestIds)).hasSize(threadCount * requestsPerThread);

    try (H2RuntimeStateStore reopened = new H2RuntimeStateStore(databasePath)) {
      assertThat(reopened.dumpRequests().loadPending()).hasSize(threadCount * requestsPerThread);
      assertThat(reopened.dumpRequests().countPending()).isEqualTo(threadCount * requestsPerThread);
    }
  }

  private static TableSchema contractSchema() {
    return TableSchema.create(
        new TableId("source", "appdb", "widgets"),
        List.of(
            new ColumnDefinition("id", "bigint", NeutralColumnType.INTEGER, true, false),
            new ColumnDefinition("name", "bigint", NeutralColumnType.INTEGER, false, true)),
        Instant.parse("2026-03-29T00:00:00Z"));
  }

  private static TableSchema observedSchema() {
    return TableSchema.create(
        new TableId("source", "appdb", "widgets"),
        List.of(
            new ColumnDefinition("id", "bigint", NeutralColumnType.INTEGER, true, false),
            new ColumnDefinition("name", "varchar(255)", NeutralColumnType.STRING, false, true),
            new ColumnDefinition("note", "json", NeutralColumnType.UNSUPPORTED, false, true)),
        Instant.parse("2026-03-29T00:05:00Z"));
  }
}
